name: Atualizar XML de Vagas
on:
  schedule:
    - cron: '0 * * * *' # Roda a cada 1 hora
  workflow_dispatch: # Permite rodar manualmente clicando num bot칚o

permissions:
  contents: write

jobs:
  update-feed:
    runs-on: ubuntu-latest
    steps:
      - name: 游닌 Baixar c칩digo do reposit칩rio
        uses: actions/checkout@v3

      - name: 游댃 Baixar XML da TOTVS
        run: |
          # Baixa o arquivo e salva como 'dados_vagas.xml'
          curl -L "https://api-centraldocandidato.totvs.app/applicant/static-files/get-xml" -o dados_vagas.xml

      - name: 游 Salvar no Reposit칩rio
        run: |
          git config --global user.name 'Bot de Vagas'
          git config --global user.email 'bot@github.com'
          
          # Verifica se houve mudan칞a
          if git diff --quiet; then
            echo "Nenhuma mudan칞a nas vagas."
          else
            git add dados_vagas.xml
            git commit -m "Atualiza칞칚o autom치tica das vagas: $(date)"
            git push
          fi
