name: Baixar Vagas TOTVS
on:
  schedule:
    - cron: '0 * * * *' # Roda a cada 1 hora automaticamente
  workflow_dispatch: # Permite você clicar num botão para rodar na hora

permissions:
  contents: write

jobs:
  download-xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Baixar XML da TOTVS
        run: |
          # O -L segue redirecionamentos, o -A simula um navegador para não ser bloqueado
          curl -L -A "Mozilla/5.0" "https://api-centraldocandidato.totvs.app/applicant/static-files/get-xml" -o vagas_totvs.xml

      - name: Salvar no Repositório
        run: |
          git config --global user.name 'Bot de Vagas'
          git config --global user.email 'bot@github.com'
          
          # Se tiver mudança, faz o commit e salva
          if [[ -n $(git status -s vagas_totvs.xml) ]]; then
            git add vagas_totvs.xml
            git commit -m "Atualizando lista de vagas"
            git push
          else
            echo "Nenhuma mudança nas vagas."
          fi
